psalm fix, replaced deprecated fuction call
dotkernel/dot-twigrenderer pull request #48
Opened 2024-07-24 09:18 UTC by Jurj-Bogdan

update for problem found in PR #47

2024-07-31 14:22 UTC, alexmerlin requested changes

2024-07-31 14:22 UTC, alexmerlin commented on psalm.xml
> -        errorBaseline="psalm-baseline.xml"
If you removed `errorBaseline` and emptied `psalm-baseline.xml` you should remove `psalm-baseline.xml` as it's no longer in use.

2024-07-31 19:19 UTC, alexmerlin approved these changes

2024-07-31 19:21 UTC, alexmerlin commented
@Jurj-Bogdan Why merge PR into the `ossbadge` branch?

2024-08-01 05:26 UTC, Jurj-Bogdan commented
> @Jurj-Bogdan Why merge PR into the `ossbadge` branch?

The initial commit was meant as a fix for @bidi47's PR #47, but the fix also failed the CI checks because of the problem found in issue #46

2024-08-01 11:20 UTC, merged